import React,{useEffect,useMemo,useState} from 'react';
import {RefreshCw,Search,Settings2} from 'lucide-react';
const labels:any={pending:'Bekliyor',confirmed:'Onaylandı',completed:'Tamamlandı',cancelled:'İptal',rejected:'Reddedildi'};
export const AppointmentsAdminTab:React.FC<{sessionToken:string|null}>=({sessionToken})=>{
 const [data,setData]=useState<any>({appointments:[],settings:null}),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[filter,setFilter]=useState('all'),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
 const headers=sessionToken?{Authorization:'Bearer '+sessionToken}:{};const load=async()=>{setLoading(true);try{const r=await fetch('/api/appointments',{headers});const d=await r.json();if(!r.ok)throw Error(d.error||'Randevular alınamadı.');setData(d)}catch(e:any){setMsg(e.message||'Yüklenemedi.')}finally{setLoading(false)}};useEffect(()=>{load()},[sessionToken]);
 const change=async(id:string,status:string)=>{const r=await fetch('/api/appointments',{method:'PATCH',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({id,status})}),d=await r.json();if(!r.ok)throw Error(d.error||'Güncellenemedi.');setData((x:any)=>({...x,appointments:x.appointments.map((a:any)=>a.id===id?d.appointment:a)}))};
 const filtered=useMemo(()=>data.appointments.filter((a:any)=>(filter==='all'||a.status===filter)&&(a.customerName+' '+a.phone+' '+a.company+' '+a.serviceName).toLowerCase().includes(q.toLowerCase())),[data,q,filter]);
 const save=async()=>{setSaving(true);try{const r=await fetch('/api/appointments',{method:'PATCH',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({action:'settings',settings:data.settings})}),d=await r.json();if(!r.ok)throw Error(d.error||'Ayarlar kaydedilemedi.');setData((x:any)=>({...x,settings:d.settings}));setMsg('Ayarlar kaydedildi.')}catch(e:any){setMsg(e.message)}finally{setSaving(false)}};
 if(loading)return <div className="bg-white rounded-3xl p-10 text-center text-sm text-slate-500"><RefreshCw className="w-6 h-6 mx-auto animate-spin mb-3"/>Randevu sistemi yükleniyor...</div>;
 const s=data.settings;return <div className="space-y-6"><div className="bg-gradient-to-r from-[#062050] to-[#173e78] text-white rounded-3xl p-7"><div className="flex justify-between gap-4 items-center"><div><div className="text-[10px] tracking-[.22em] text-amber-300 font-black">RANDEVU MERKEZİ</div><h2 className="text-2xl font-serif font-bold mt-1">Randevular & Müsaitlik</h2><p className="text-sm text-white/65 mt-2">Talepleri yönetin ve çalışma saatlerini belirleyin.</p></div><button onClick={load} className="px-4 py-2 rounded-xl bg-white/10 text-xs font-bold"><RefreshCw className="w-4 h-4 inline mr-2"/>Yenile</button></div></div>
 <div className="grid lg:grid-cols-[1.35fr_.65fr] gap-6"><section className="bg-white rounded-3xl border border-slate-200 overflow-hidden"><div className="p-5 border-b flex flex-wrap gap-3 justify-between"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Müşteri, telefon, firma..." className="pl-9 pr-3 py-2.5 rounded-xl border text-sm"/></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="px-3 py-2.5 rounded-xl border text-sm"><option value="all">Tümü</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v as string}</option>)}</select></div><div className="divide-y">{filtered.length===0?<div className="p-10 text-center text-sm text-slate-500">Randevu bulunamadı.</div>:filtered.map((a:any)=><div key={a.id} className="p-5"><div className="flex flex-wrap justify-between gap-4"><div><div className="font-bold text-[#102f59]">{a.customerName} <span className="text-[10px] font-bold px-2 py-1 rounded-full bg-slate-100 ml-2">{labels[a.status]}</span></div><div className="mt-2 text-sm font-semibold">{a.serviceName}</div><div className="mt-1 text-xs text-slate-500">{a.date} · {a.time} · {a.phone}{a.company?' · '+a.company:''}</div>{a.email&&<div className="mt-1 text-xs text-slate-500">{a.email}</div>}{a.note&&<div className="mt-2 text-xs bg-slate-50 rounded-xl p-3">{a.note}</div>}</div><div className="flex gap-2 items-start"><a href={'tel:'+a.phone} className="px-3 py-2 rounded-xl border text-xs font-bold">Ara</a><select value={a.status} onChange={e=>change(a.id,e.target.value).catch(err=>setMsg(err.message))} className="px-3 py-2 rounded-xl border text-xs font-bold">{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{v as string}</option>)}</select></div></div></div>)}</div></section>
 <section className="bg-white rounded-3xl border border-slate-200 p-6"><div className="flex items-center gap-2 font-bold text-[#102f59]"><Settings2 className="w-5 h-5"/>Randevu ayarları</div>{s&&<><label className="mt-5 flex justify-between p-3 rounded-xl bg-slate-50 text-sm font-bold">Sistem açık<input type="checkbox" checked={s.enabled} onChange={e=>setData((x:any)=>({...x,settings:{...x.settings,enabled:e.target.checked}}))}/></label><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs font-bold">Slot<select value={s.slotMinutes} onChange={e=>setData((x:any)=>({...x,settings:{...x.settings,slotMinutes:Number(e.target.value)}}))} className="mt-1 w-full p-2.5 rounded-xl border"><option value="15">15 dk</option><option value="30">30 dk</option><option value="60">60 dk</option></select></label><label className="text-xs font-bold">Minimum önceden<select value={s.minAdvanceHours} onChange={e=>setData((x:any)=>({...x,settings:{...x.settings,minAdvanceHours:Number(e.target.value)}})} className="mt-1 w-full p-2.5 rounded-xl border"><option value="1">1 saat</option><option value="2">2 saat</option><option value="4">4 saat</option><option value="24">24 saat</option></select></label></div><div className="mt-5 space-y-2">{Object.entries(s.workingHours).sort((a:any,b:any)=>Number(a[0])-Number(b[0])).map(([d,h]:any)=>{const n=['Pazar','Pazartesi','Salı','Çarşamba','Perşembe','Cuma','Cumartesi'];return <div key={d} className="grid grid-cols-[1fr_85px_85px] gap-2 items-center text-xs"><span className="font-bold">{n[Number(d)]}</span><input type="time" value={h.start} disabled={!h.enabled} onChange={e=>setData((x:any)=>({...x,settings:{...x.settings,workingHours:{...x.settings.workingHours,[d]:{...h,start:e.target.value}}}}))} className="p-2 rounded-lg border"/><input type="time" value={h.end} disabled={!h.enabled} onChange={e=>setData((x:any)=>({...x,settings:{...x.settings,workingHours:{...x.settings.workingHours,[d]:{...h,end:e.target.value}}}})} className="p-2 rounded-lg border"/></div>})}</div><button onClick={save} disabled={saving} className="mt-5 w-full py-3 rounded-xl bg-[#102f59] text-white font-bold text-sm">{saving?'Kaydediliyor...':'Ayarları Kaydet'}</button>{msg&&<div className="mt-3 text-xs font-semibold text-slate-600">{msg}</div>}</>}</section></div></div>;
};