import React,{useEffect,useMemo,useState} from 'react';
import {CalendarDays,CheckCircle2,Clock3,MapPin,Phone,Mail,User,Building2,Loader2,MessageCircle} from 'lucide-react';
import {SitePageShell} from './SitePageShell';
import {CONTACT_DATA} from '../constants/data';
const SERVICES=[{id:'showroom',name:'Showroom / Koleksiyon Görüşmesi',duration:45,desc:'Yeni sezon modellerini birlikte inceleyelim.'},{id:'wholesale',name:'Toptan Satış Görüşmesi',duration:30,desc:'Mağazanız için model ve sipariş planlaması.'},{id:'models',name:'Model & Numara Görüşmesi',duration:30,desc:'Model, renk ve numara seçeneklerini görüşelim.'},{id:'custom',name:'Özel Görüşme',duration:30,desc:'Size uygun bir görüşme zamanı oluşturalım.'}];
const pad=(n:number)=>String(n).padStart(2,'0'),ds=(d:Date)=>d.getFullYear()+'-'+pad(d.getMonth()+1)+'-'+pad(d.getDate());
const pretty=(s:string)=>new Date(s+'T12:00:00').toLocaleDateString('tr-TR',{weekday:'long',day:'2-digit',month:'long'});
export const AppointmentPage:React.FC<any>=({onAdminClick,openLegal})=>{
 const [service,setService]=useState('showroom'),[date,setDate]=useState(ds(new Date())),[slots,setSlots]=useState<string[]>([]),[time,setTime]=useState(''),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[done,setDone]=useState<any>(null);
 const [form,setForm]=useState({customerName:'',phone:'',email:'',company:'',note:''});const selected=SERVICES.find(x=>x.id===service)!;
 const days=useMemo(()=>Array.from({length:21},(_,i)=>{const d=new Date();d.setDate(d.getDate()+i);return ds(d)}),[]);
 const load=async()=>{setLoading(true);setError('');setTime('');try{const r=await fetch('/api/appointments?action=slots&date='+date+'&service='+service,{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Saatler alınamadı.');setSlots(d.slots||[])}catch(e:any){setSlots([]);setError(e.message||'Saatler yüklenemedi.')}finally{setLoading(false)}};
 useEffect(()=>{load()},[date,service]);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!time)return setError('Lütfen uygun bir saat seçin.');setSaving(true);setError('');try{const r=await fetch('/api/appointments',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,serviceId:service,date,time})}),d=await r.json();if(!r.ok)throw Error(d.error||'Randevu oluşturulamadı.');setDone(d.appointment)}catch(e:any){setError(e.message||'Randevu oluşturulamadı.');load()}finally{setSaving(false)}};
 const shell={onAdminClick,legal:{open:openLegal!}};
 if(done)return <SitePageShell title="Randevu talebiniz alındı" eyebrow="RANDEVU" intro="Talebinizi kaydettik. Ekibimiz randevuyu onaylamak için sizinle iletişime geçecektir." activePath="/randevu" {...shell}><section className="max-w-3xl mx-auto px-5 py-16"><div className="bg-white rounded-[2rem] border border-emerald-200 shadow-xl p-8 text-center"><CheckCircle2 className="w-14 h-14 mx-auto text-emerald-600"/><div className="mt-4 text-xs font-black tracking-[.2em] text-[#8b6a2b]">TALEP #{done.id.slice(0,8)}</div><h2 className="mt-2 text-3xl font-serif-luxury font-bold text-[#102f59]">Randevunuz kaydedildi</h2><div className="mt-6 grid sm:grid-cols-2 gap-3 text-left"><div className="p-4 rounded-2xl bg-slate-50"><b>Görüşme</b><div className="mt-1 text-sm">{done.serviceName}</div></div><div className="p-4 rounded-2xl bg-slate-50"><b>Tarih / Saat</b><div className="mt-1 text-sm">{pretty(done.date)} · {done.time}</div></div></div><p className="mt-6 text-sm text-slate-600">Kesin onay için ekibimiz sizinle telefon veya e-posta üzerinden iletişime geçecektir.</p><a href={'https://wa.me/'+CONTACT_DATA.whatsapp+'?text='+encodeURIComponent('Merhaba, randevu talebim hakkında bilgi almak istiyorum. Randevu no: '+done.id.slice(0,8))} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 mt-5 rounded-full bg-[#25D366] text-white px-6 py-3 font-bold text-sm"><MessageCircle className="w-4 h-4"/> WhatsApp'tan yaz</a><button onClick={()=>setDone(null)} className="block mx-auto mt-4 text-sm font-bold text-[#102f59]">Yeni randevu oluştur</button></div></section></SitePageShell>;
 return <SitePageShell title="Randevu ayarlayın" eyebrow="RANDEVU" intro="İrem Comfort ekibinden bir yetkiliyle görüşmek için uygun gün ve saatinizi seçin." activePath="/randevu" {...shell}><section className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-10 py-10 sm:py-16"><div className="grid lg:grid-cols-[1.1fr_.9fr] gap-7 items-start">
 <div className="space-y-6"><div className="bg-white rounded-[2rem] border border-slate-200 p-6 sm:p-8"><div className="flex items-center gap-3"><div className="w-11 h-11 rounded-2xl bg-[#102f59] text-white grid place-items-center"><CalendarDays/></div><div><h2 className="text-xl font-bold text-[#102f59]">Görüşme türü</h2><p className="text-xs text-slate-500">Size uygun görüşmeyi seçin.</p></div></div><div className="mt-6 grid sm:grid-cols-2 gap-3">{SERVICES.map(s=><button type="button" key={s.id} onClick={()=>setService(s.id)} className={'text-left p-4 rounded-2xl border transition '+(service===s.id?'border-[#102f59] bg-[#102f59]/5 ring-2 ring-[#102f59]/10':'border-slate-200 hover:border-[#102f59]/40')}><div className="font-bold text-sm text-[#102f59]">{s.name}</div><div className="mt-1 text-xs text-slate-500">{s.desc}</div><div className="mt-3 inline-flex items-center gap-1.5 text-[11px] font-bold text-[#8b6a2b]"><Clock3 className="w-3.5 h-3.5"/>{s.duration} dakika</div></button>)}</div></div>
 <div className="bg-white rounded-[2rem] border border-slate-200 p-6 sm:p-8"><div className="flex justify-between"><div><h2 className="text-xl font-bold text-[#102f59]">Gün ve saat</h2><p className="text-xs text-slate-500">Önümüzdeki 21 gün.</p></div><CalendarDays className="text-[#8b6a2b]"/></div><div className="mt-5 flex gap-2 overflow-x-auto pb-2">{days.map(d=><button key={d} type="button" onClick={()=>setDate(d)} className={'min-w-[92px] p-3 rounded-2xl border text-left '+(date===d?'bg-[#102f59] text-white border-[#102f59]':'border-slate-200 text-[#102f59]')}><div className="text-[10px] uppercase font-bold opacity-70">{new Date(d+'T12:00:00').toLocaleDateString('tr-TR',{weekday:'short'})}</div><div className="mt-1 font-black text-lg">{new Date(d+'T12:00:00').getDate()}</div><div className="text-[10px] opacity-70">{new Date(d+'T12:00:00').toLocaleDateString('tr-TR',{month:'short'})}</div></button>)}</div><div className="mt-6"><div className="text-sm font-bold text-[#102f59] mb-3">Uygun saatler</div>{loading?<div className="py-8 text-center text-sm text-slate-500"><Loader2 className="w-5 h-5 mx-auto animate-spin"/></div>:slots.length?<div className="grid grid-cols-3 sm:grid-cols-4 gap-2">{slots.map(s=><button type="button" key={s} onClick={()=>setTime(s)} className={'py-3 rounded-xl border text-sm font-bold '+(time===s?'bg-[#8b6a2b] text-white border-[#8b6a2b]':'border-slate-200 text-[#102f59] hover:border-[#8b6a2b]')}>{s}</button>)}</div>:<div className="rounded-2xl bg-slate-50 p-5 text-sm text-slate-500">Bu gün için uygun saat bulunmuyor.</div>}</div></div></div>
 <form onSubmit={submit} className="bg-white rounded-[2rem] border border-slate-200 p-6 sm:p-8 lg:sticky lg:top-28 shadow-sm"><div className="text-xs font-black tracking-[.2em] uppercase text-[#8b6a2b]">Randevu bilgileri</div><h2 className="mt-2 text-2xl font-serif-luxury font-bold text-[#102f59]">Seçiminizi tamamlayın</h2><div className="mt-5 p-4 rounded-2xl bg-[#102f59] text-white"><div className="text-xs opacity-70">Seçilen görüşme</div><div className="mt-1 font-bold">{selected.name}</div><div className="mt-1 text-xs text-white/70">{pretty(date)} · {time||'Saat seçilmedi'}</div></div><div className="mt-5 space-y-3">{[[User,'customerName','Ad Soyad','Ad soyad'],[Phone,'phone','Telefon','0532...'],[Mail,'email','E-posta','ornek@mail.com'],[Building2,'company','Firma / Mağaza','Firma adı']].map(([I,k,l,p]:any)=><label key={k} className="block"><span className="text-xs font-bold text-slate-700">{l}{['customerName','phone'].includes(k)&&<span className="text-rose-500"> *</span>}</span><div className="relative mt-1.5"><I className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input required={['customerName','phone'].includes(k)} type={k==='email'?'email':'text'} value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={p} className="w-full pl-10 pr-3 py-3 rounded-xl border border-slate-200 text-sm outline-none focus:border-[#102f59]"/></div></label>)}<label className="block"><span className="text-xs font-bold text-slate-700">Not / Talebiniz</span><textarea value={form.note} onChange={e=>setForm({...form,note:e.target.value})} rows={4} placeholder="Görüşmede konuşmak istediğiniz konu..." className="mt-1.5 w-full p-3 rounded-xl border border-slate-200 text-sm outline-none focus:border-[#102f59] resize-none"/></label></div>{error&&<div className="mt-4 rounded-xl bg-rose-50 border border-rose-200 p-3 text-xs font-semibold text-rose-700">{error}</div>}<button disabled={saving||!time} className="mt-5 w-full rounded-xl bg-[#102f59] text-white py-3.5 font-extrabold text-sm disabled:opacity-40 flex items-center justify-center gap-2">{saving?<Loader2 className="w-4 h-4 animate-spin"/>:<CheckCircle2 className="w-4 h-4"/>}{saving?'Kaydediliyor...':'Randevu Talebi Oluştur'}</button><div className="mt-4 flex gap-2 text-[11px] text-slate-500"><MapPin className="w-4 h-4 shrink-0 text-[#8b6a2b]"/><span>Çalışma saatleri Türkiye saatine göre uygulanır. Randevu kesinleştiğinde size ayrıca bilgi verilir.</span></div></form></div></section></SitePageShell>;
};