import React, { useMemo, useState } from 'react';
import { ArrowLeft, Check, Copy, MessageCircle, Share2 } from 'lucide-react';
import { useAppImages } from '../context/ImageContext';
import { COLLECTION_ITEMS, PREMIUM_PRODUCT_IMAGE_FALLBACKS } from '../constants/data';
import { SitePageShell } from './SitePageShell';

export const ProductDetailPage: React.FC<{productId:string;onAdminClick?:()=>void;openLegal?:(d:any)=>void}> = ({productId,onAdminClick,openLegal}) => {
 const {collectionItems, images}=useAppImages();
 const item=(collectionItems?.length?collectionItems:COLLECTION_ITEMS).find(x=>x.id===productId);
 const [copied,setCopied]=useState(false);
 if(!item) return <SitePageShell title="Ürün bulunamadı" activePath="/urunler" onAdminClick={onAdminClick} legal={{open:openLegal!}}><div className="max-w-7xl mx-auto px-5 py-20"><a href="/urunler" className="font-bold text-[#102f59]">Ürünlere dön</a></div></SitePageShell>;
 const productImages=useMemo(()=>[images.collectionImages[item.id]?.image||item.image||PREMIUM_PRODUCT_IMAGE_FALLBACKS[item.id],images.collectionImages[item.id]?.secondaryImage||item.secondaryImage,...(item.colors||[]).map(c=>c.image)].filter(Boolean),[images,item]);
 const share=async()=>{const url=`${window.location.origin}/urunler/${encodeURIComponent(item.id)}`;try{if(navigator.share){await navigator.share({title:item.name,text:item.tagline,url});}else{await navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),1800)}}catch{}}
 return <SitePageShell title={item.name} eyebrow={item.category} intro={item.subtitle} activePath="/urunler" onAdminClick={onAdminClick} legal={{open:openLegal!}}><section className="max-w-7xl mx-auto px-5 sm:px-8 lg:px-10 py-12 sm:py-20"><a href="/urunler" className="inline-flex items-center gap-2 text-sm font-bold text-[#102f59] mb-7"><ArrowLeft className="w-4 h-4"/> Ürünlere dön</a><div className="grid lg:grid-cols-[1.05fr_.95fr] gap-8"><div className="bg-white rounded-[2rem] border border-slate-200 overflow-hidden"><img src={productImages[0]} className="w-full aspect-square object-cover"/><div className="grid grid-cols-4 gap-2 p-3">{productImages.slice(0,4).map((src,i)=><img key={i} src={src} className="aspect-square object-cover rounded-xl border border-slate-200"/>)}</div></div><div className="bg-white rounded-[2rem] border border-slate-200 p-7 sm:p-10"><div className="text-[11px] uppercase tracking-[.2em] text-[#8b6a2b] font-bold">TOPTAN ÜRÜN BİLGİSİ</div><h2 className="mt-3 text-3xl font-serif-luxury font-bold text-[#102f59]">{item.tagline}</h2><p className="mt-5 text-sm text-slate-600 leading-relaxed">{item.description}</p><div className="mt-7 grid sm:grid-cols-2 gap-3">{item.features.slice(0,4).map(f=><div key={f} className="flex gap-2 text-sm text-slate-700"><Check className="w-4 h-4 text-[#8b6a2b] mt-0.5"/>{f}</div>)}</div><div className="mt-8 p-5 rounded-2xl bg-[#f7f5f1] border border-slate-200"><div className="text-xs font-bold text-slate-500">NUMARA / TABAN</div><div className="mt-1 font-bold text-[#102f59]">{item.dimensions}</div></div><div className="mt-7 flex flex-wrap gap-3"><a href="/toptan-satis" className="inline-flex items-center gap-2 rounded-full bg-[#102f59] text-white px-5 py-3 font-bold text-sm">Toptan teklif iste <MessageCircle className="w-4 h-4"/></a><button onClick={share} className="inline-flex items-center gap-2 rounded-full border border-[#102f59]/20 px-5 py-3 font-bold text-sm text-[#102f59]">{copied?<Copy className="w-4 h-4"/>:<Share2 className="w-4 h-4"/>}{copied?'Link kopyalandı':'Ürün linkini paylaş'}</button></div></div></div></section></SitePageShell>;
};
