import type { VercelRequest,VercelResponse } from '@vercel/node';
import nodemailer from 'nodemailer';
import {createCipheriv,createDecipheriv,createHmac,randomBytes,randomUUID,timingSafeEqual} from 'node:crypto';
type Status='pending'|'confirmed'|'completed'|'cancelled'|'rejected';
type Appointment={id:string;serviceId:string;serviceName:string;duration:number;date:string;time:string;customerName:string;phone:string;email:string;company:string;note:string;status:Status;createdAt:string;updatedAt:string};
type Settings={enabled:boolean;timezone:string;slotMinutes:number;minAdvanceHours:number;maxDaysAhead:number;workingHours:Record<string,{enabled:boolean;start:string;end:string}>;blockedDates:string[];blockedSlots:string[]};
type Store={appointments:Appointment[];settings:Settings};
const OWNER=process.env.PRIVATE_CATALOG_GITHUB_OWNER||'kadirkarga25-rgb',REPO=process.env.PRIVATE_CATALOG_GITHUB_REPO||'irem-comfort',BRANCH=process.env.PRIVATE_CATALOG_DATA_BRANCH||'private-catalog-data',TOKEN=process.env.GITHUB_PRIVATE_CATALOG_TOKEN||process.env.GITHUB_TOKEN||'',KEY=process.env.PRIVATE_CATALOG_ENCRYPTION_KEY||'',SECRET=process.env.ADMIN_SESSION_SECRET||process.env.ADMIN_PASSWORD||'irem-comfort-admin-session-secret',PATH='private-catalog-data/appointments.enc',API='https://api.github.com';
const SERVICES:Record<string,{name:string;duration:number}>={showroom:{name:'Showroom / Koleksiyon Görüşmesi',duration:45},wholesale:{name:'Toptan Satış Görüşmesi',duration:30},models:{name:'Model & Numara Görüşmesi',duration:30},custom:{name:'Özel Görüşme',duration:30}};
const DEFAULT:Settings={enabled:true,timezone:'Europe/Istanbul',slotMinutes:30,minAdvanceHours:2,maxDaysAhead:60,workingHours:{'0':{enabled:false,start:'10:00',end:'15:00'},'1':{enabled:true,start:'09:00',end:'18:00'},'2':{enabled:true,start:'09:00',end:'18:00'},'3':{enabled:true,start:'09:00',end:'18:00'},'4':{enabled:true,start:'09:00',end:'18:00'},'5':{enabled:true,start:'09:00',end:'18:00'},'6':{enabled:false,start:'10:00',end:'15:00'}},blockedDates:[],blockedSlots:[]};
const out=(res:VercelResponse,s:number,d:any)=>{res.setHeader('Cache-Control','private,no-store');return res.status(s).json(d)};
const kb=()=>{const b=Buffer.from(KEY,'base64');if(b.length!==32)throw Error('PRIVATE_CATALOG_ENCRYPTION_KEY 32 bayt Base64 olmalı.');return b};
const enc=(b:Buffer)=>{const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',kb(),iv),d=Buffer.concat([c.update(b),c.final()]);return Buffer.from(JSON.stringify({iv:iv.toString('base64'),tag:c.getAuthTag().toString('base64'),data:d.toString('base64')}))};
const dec=(b:Buffer)=>{const x=JSON.parse(b.toString()),d=createDecipheriv('aes-256-gcm',kb(),Buffer.from(x.iv,'base64'));d.setAuthTag(Buffer.from(x.tag,'base64'));return Buffer.concat([d.update(Buffer.from(x.data,'base64')),d.final()])};
async function gh(p:string,i:RequestInit={}){if(!TOKEN)throw Error('GITHUB_PRIVATE_CATALOG_TOKEN eksik.');return fetch(API+'/repos/'+OWNER+'/'+REPO+p,{...i,headers:{Authorization:'Bearer '+TOKEN,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json',...(i.headers||{})}})}
async function branch(){const r=await gh('/git/ref/heads/'+BRANCH);if(r.ok)return;if(r.status!==404)throw Error('GitHub veri dalı okunamadı.');const b=await gh('/git/ref/heads/main'),j:any=await b.json();const c=await gh('/git/refs',{method:'POST',body:JSON.stringify({ref:'refs/heads/'+BRANCH,sha:j.object.sha})});if(!c.ok&&c.status!==422)throw Error('GitHub veri dalı oluşturulamadı.')}
async function read(){const r=await gh('/contents/'+PATH+'?ref='+encodeURIComponent(BRANCH));if(r.status===404)return null;if(!r.ok)throw Error('Randevu verisi okunamadı.');const j:any=await r.json();return {bytes:Buffer.from(String(j.content).replace(/\n/g,''),'base64'),sha:j.sha}}
async function store():Promise<{s:Store;sha?:string}>{const f=await read();if(!f)return {s:{appointments:[],settings:DEFAULT}};const x:any=JSON.parse(dec(f.bytes).toString());return {s:{appointments:Array.isArray(x.appointments)?x.appointments:[],settings:{...DEFAULT,...x.settings,workingHours:{...DEFAULT.workingHours,...(x.settings?.workingHours||{})}}},sha:f.sha}}
async function save(s:Store){const f=await read(),r=await gh('/contents/'+PATH,{method:'PUT',body:JSON.stringify({message:'Update encrypted appointment data',branch:BRANCH,content:enc(Buffer.from(JSON.stringify(s))).toString('base64'),...(f?{sha:f.sha}:{})})});if(!r.ok){const j:any=await r.json().catch(()=>({}));throw Error(j.message||'Randevu verisi kaydedilemedi.');}}
function isAdmin(req:VercelRequest){const h=String(req.headers.authorization||'');if(!h.startsWith('Bearer '))return false;const t=h.slice(7);if(!t.startsWith('sess2_'))return false;const [p,s]=t.slice(6).split('.');if(!p||!s)return false;try{const e=createHmac('sha256',SECRET).update(p).digest('base64url');if(!timingSafeEqual(Buffer.from(s),Buffer.from(e)))return false;return Number(JSON.parse(Buffer.from(p,'base64url').toString()).exp)>Date.now()}catch{return false}}
const mins=(t:string)=>{const [h,m]=t.split(':').map(Number);return h*60+m},hm=(n:number)=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
const day=(d:string)=>new Date(d+'T12:00:00+03:00').getDay();
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Istanbul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const nowM=()=>mins(new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Istanbul',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()));
const validDate=(d:string)=>/^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d+'T12:00:00+03:00'));
const clean=(v:any,n:number)=>String(v||'').trim().slice(0,n);
function slots(s:Store,date:string,service:string){const svc=SERVICES[service],w=s.settings.workingHours[String(day(date))];if(!svc||!w?.enabled||s.settings.blockedDates.includes(date))return [];const max=new Date(today()+'T12:00:00+03:00');const target=new Date(date+'T12:00:00+03:00');const diff=Math.round((target.getTime()-max.getTime())/86400000);if(diff<0||diff>s.settings.maxDaysAhead)return [];const a:string[]=[],start=mins(w.start),end=mins(w.end),step=Math.max(15,s.settings.slotMinutes);for(let m=start;m+svc.duration<=end;m+=step){const t=hm(m),blocked=s.settings.blockedSlots.includes(date+' '+t)||s.appointments.some(x=>x.date===date&&['pending','confirmed'].includes(x.status)&&mins(x.time)<m+svc.duration&&m<mins(x.time)+x.duration);if(!blocked&&!(date===today()&&m<nowM()+s.settings.minAdvanceHours*60))a.push(t)}return a}
async function mail(a:Appointment){const pass=process.env.SMTP_PASS||'',user=process.env.SMTP_USER||'info@iremcomfort.com';if(!pass)return;const tr=nodemailer.createTransport({host:process.env.SMTP_HOST||'smtp.gmail.com',port:Number(process.env.SMTP_PORT||465),secure:process.env.SMTP_SECURE?process.env.SMTP_SECURE==='true':true,auth:{user,pass},tls:{rejectUnauthorized:false}}),html='<div style="font-family:Arial;max-width:620px;margin:auto;padding:24px;background:#f8fafc"><div style="background:#0d223e;color:#fff;padding:22px;border-radius:14px"><b>İREM COMFORT — RANDEVU</b></div><div style="background:#fff;padding:22px;margin-top:10px;border-radius:14px"><p><b>Görüşme:</b> '+a.serviceName+'</p><p><b>Tarih/Saat:</b> '+a.date+' '+a.time+'</p><p><b>Müşteri:</b> '+a.customerName+'</p><p><b>Telefon:</b> '+a.phone+'</p><p><b>E-posta:</b> '+(a.email||'-')+'</p><p><b>Firma:</b> '+(a.company||'-')+'</p><p><b>Not:</b> '+(a.note||'-')+'</p></div></div>';try{await tr.sendMail({from:'"İrem Comfort" <'+user+'>',to:process.env.APPOINTMENT_ADMIN_EMAILS||'kargakadir4525@gmail.com, info@iremcomfort.com',subject:'[YENİ RANDEVU] '+a.date+' '+a.time+' — '+a.customerName,html});if(a.email)await tr.sendMail({from:'"İrem Comfort" <'+user+'>',to:a.email,subject:'İrem Comfort — Randevu talebiniz alındı',html})}catch(e){console.error(e)}}
export default async function handler(req:VercelRequest,res:VercelResponse){if(!TOKEN||!KEY)return out(res,503,{success:false,error:'Randevu sistemi için GitHub token ve şifreleme anahtarı gerekli.'});try{await branch();const {s}=await store();
 if(req.method==='GET'&&req.query.action==='slots'){const d=clean(req.query.date,10),v=clean(req.query.service,30);if(!validDate(d)||!SERVICES[v])return out(res,400,{error:'Geçersiz tarih veya hizmet.'});return out(res,200,{enabled:s.settings.enabled,slots:s.settings.enabled?slots(s,d,v):[],timezone:s.settings.timezone})}
 if(req.method==='POST'&&!isAdmin(req)){if(!s.settings.enabled)return out(res,409,{error:'Randevu sistemi şu anda kapalı.'});const b=req.body||{},v=clean(b.serviceId,30),d=clean(b.date,10),t=clean(b.time,5),svc=SERVICES[v];if(!svc||!validDate(d)||!slots(s,d,v).includes(t))return out(res,409,{error:'Bu saat artık müsait değil. Lütfen başka bir saat seçin.'});const name=clean(b.customerName,100),phone=clean(b.phone,30),email=clean(b.email,160);if(name.length<2||phone.length<7)return out(res,400,{error:'Ad soyad ve telefon zorunludur.'});if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return out(res,400,{error:'E-posta geçersiz.'});const a:Appointment={id:randomUUID(),serviceId:v,serviceName:svc.name,duration:svc.duration,date:d,time:t,customerName:name,phone,email,company:clean(b.company,120),note:clean(b.note,800),status:'pending',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};s.appointments.unshift(a);await save(s);await mail(a);return out(res,201,{success:true,appointment:{id:a.id,date:d,time:t,serviceName:svc.name,status:a.status}})}
 if(!isAdmin(req))return out(res,401,{error:'Yönetici oturumu gerekli.'});
 if(req.method==='GET')return out(res,200,{appointments:s.appointments,settings:s.settings,services:Object.entries(SERVICES).map(([id,x])=>({id,...x}))});
 if(req.method==='PATCH'){const b=req.body||{};if(b.action==='settings'){s.settings={...s.settings,...b.settings,workingHours:{...s.settings.workingHours,...(b.settings?.workingHours||{})}};await save(s);return out(res,200,{success:true,settings:s.settings})}const a=s.appointments.find(x=>x.id===b.id);if(!a)return out(res,404,{error:'Randevu bulunamadı.'});if(['pending','confirmed','completed','cancelled','rejected'].includes(b.status)){a.status=b.status;a.updatedAt=new Date().toISOString();await save(s);return out(res,200,{success:true,appointment:a})}return out(res,400,{error:'Bilinmeyen işlem.'})}return out(res,405,{error:'Method not allowed.'})
}catch(e:any){console.error(e);return out(res,500,{success:false,error:e?.message||'Randevu sistemi hatası.'})}}